add jms based cache invalidation configuration
wso2/docs-apim pull request #2056
Opened 2020-10-12 09:32 UTC by tharindu1st

## Purpose
Add JMS based cache invalidation configurations

2020-10-12 23:30 UTC, isharac requested changes

2020-10-12 23:30 UTC, isharac commented on en/docs/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup.md
> +3. Optionally Add following configuration to enable Distributed JMS based cache invalidation within Key Manager nodes.
Do we need to say 'JMS based' cache invalidation? because if that is the only option do we need to explicitly mention that it is JMS based?

2020-10-26 12:35 UTC, isharac approved these changes

2020-10-29 15:42 UTC, Mariangela approved these changes

2020-10-29 15:42 UTC, merged

2020-10-29 15:51 UTC, Mariangela commented
@tharindu1st , please make sure to send these changes to the 3.2.0 and master branches as well if applicable.