[3.1.0] Add docs to configure IS as extenral IDP using OIDC
wso2/docs-apim pull request #2068
Opened 2020-10-14 11:08 UTC by vithu30

## Purpose
> Fixes https://github.com/wso2/docs-apim/issues/922

2020-11-03 13:54 UTC, Mariangela commented
@vithu30 , can you please address the review comment regarding the image name and fix the merge conflict. Please note that I have made changes in your fork. So please make sure to pull those changes to your local repo before making any changes.

2020-11-03 14:36 UTC, Mariangela requested changes
Please see the comment.

2020-11-04 01:53 UTC, vithu30 commented
@Mariangela, resolved the conflicts.

2020-11-04 06:03 UTC, Mariangela commented on en/docs/install-and-setup/setup/sso/configuring-identity-server-as-external-idp-using-saml.md
> +    [![upload-certificate-in-SP-for-saml2-sso.png]({{base_path}}/assets/img/setup-and-install/upload-certificate-in-SP-for-saml2-sso.png)]({{base_path}}/assets/img/setup-and-install/upload-certificat
did you rename the image itself? I do not see it under the physical files that have been uploaded.

2020-11-04 06:18 UTC, Mariangela approved these changes

2020-11-04 06:19 UTC, merged