[3.2.0] Adding Docs for Setting up a user for the Admin Portal
wso2/docs-apim pull request #2211
Opened 2020-11-06 09:13 UTC by Sarangan0219

### Purpose

Fixes https://github.com/wso2/docs-apim/issues/1624

2020-11-06 09:14 UTC, chamilaadhi approved these changes

2020-11-27 06:43 UTC, Mariangela approved these changes

2020-11-27 08:26 UTC, Mariangela requested changes

2020-11-27 08:26 UTC, Mariangela commented on en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md
> +
Image not showing
<img width="767" alt="Screenshot 2020-11-27 at 13 50 33" src="https://user-images.githubusercontent.com/5195851/100427179-11761880-30b8-11eb-99df-05919b6955e9.png">

2020-11-27 08:26 UTC, Mariangela commented on en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md
> +    ![Minimum Version of Admin Portal]({{base_path}}/assets/img/administer/minimum-version-admin-portal.png)
Image not showing
<img width="885" alt="Screenshot 2020-11-27 at 13 50 43" src="https://user-images.githubusercontent.com/5195851/100427229-2e125080-30b8-11eb-920a-8a9003626f16.png">

2020-11-27 08:26 UTC, Mariangela commented on en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md
> +    ![Add admin manager user]({{base_path}}/assets/img/administer/add-manager-user.png)
Image not showing
<img width="939" alt="Screenshot 2020-11-27 at 13 50 50" src="https://user-images.githubusercontent.com/5195851/100427312-484c2e80-30b8-11eb-81f6-7dded0d6c157.png">

2020-11-27 08:26 UTC, Mariangela commented on en/docs/administer/managing-users-and-roles/managing-users-for-admin-portal.md
> +    ![Assign admin portal user role]({{base_path}}/assets/img/administer/add-admin-manager-role-to-user.png)
Image not showing

2020-11-27 08:27 UTC, Mariangela commented
@Sarangan0219 , looks like you have forgotten to attach some images along with this PR. Please check my review comments. Also note that I updated your PR after reviewing it. I have sent the changes to your branch.

2020-11-27 10:51 UTC, Mariangela approved these changes

2020-11-27 10:51 UTC, merged

2020-11-27 10:54 UTC, Mariangela commented
@Sarangan0219 , is this fix applicable to 3.0.0 and 3.1.0? Please send this fix to the master branch as well.