add application level token expiry docs
wso2/docs-apim pull request #2223
Opened 2020-11-09 16:23 UTC by tharindu1st

2020-11-09 17:49 UTC, bhathiya requested changes

2020-11-09 17:49 UTC, bhathiya commented on en/docs/learn/consume-api/manage-application/generate-keys/obtain-access-token/changing-the-default-token-expiration-time.md
> +You can configure the token expiration time in Application level as follows.
```suggestion
You can configure the token expiration time at the application-level as follows.
```

2020-11-09 17:49 UTC, bhathiya commented on en/docs/learn/consume-api/manage-application/generate-keys/obtain-access-token/changing-the-default-token-expiration-time.md
> +2. Click Applications to navigate to the applications listing page and click on the respective application for which you want to generate keys.
```suggestion
2. Click "Applications" to navigate to the applications listing page and click on the respective application for which you want to generate keys.
```

2020-11-09 17:49 UTC, bhathiya commented on en/docs/learn/consume-api/manage-application/generate-keys/obtain-access-token/changing-the-default-token-expiration-time.md
> +3. Click Oauth2 Tokens under Production Keys,set the validity period as follows.
```suggestion
3. Click "Oauth2 Tokens" under "Production Keys", and set the validity period as follows.
```

2020-11-09 17:49 UTC, bhathiya commented on en/docs/learn/consume-api/manage-application/generate-keys/obtain-access-token/changing-the-default-token-expiration-time.md
> +
```suggestion
```

2020-11-30 07:16 UTC, bhathiya approved these changes

2020-11-30 13:11 UTC, Mariangela approved these changes

2020-11-30 13:11 UTC, merged