Add details to keep system roles without being deleted during the provisioning process
wso2/docs-apim pull request #2267
Opened 2020-11-19 09:45 UTC by ruthryi

- Clean [1]
- Fix #2257

2020-11-25 07:52 UTC, Prasadi-R requested changes

2020-11-25 07:52 UTC, Prasadi-R commented on en/docs/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
> +    When Just-In-Time Provisioning is enabled, the user details will be saved in the API Manager user store. User profile details will be update via federation following each login event. To preserve
The above sentence, ("To preserve the user profile details without any changes you need to enable the 'SystemRolesRetainedProvisionHandler'.") needs to be corrected as follows,
"To preserve previously assigned system roles (Application/, Workflow/) in the user profile, you need to enable the 'SystemRolesRetainedProvisionHandler'."

2020-11-25 07:52 UTC, Prasadi-R commented on en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
> +        When Just-In-Time Provisioning is enabled, the user details will be saved in the API Manager user store. User profile details will be update via federation following each login event. To pres
The above sentence, ("To preserve the user profile details without any changes you need to enable the 'SystemRolesRetainedProvisionHandler'.") needs to be corrected as follows,
"To preserve previously assigned system roles (Application/, Workflow/) in the user profile, you need to enable the 'SystemRolesRetainedProvisionHandler'."

2020-11-25 07:52 UTC, Prasadi-R commented on en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md
> +    You need to enable this because OKTA uses the email as a username by default. To  use the email as the username in WSO2 API Manager you have to enable it, since it not enabled by default. Once en
"OKTA uses the email as a username by default" -> OKTA uses the email as the username by default

2020-12-05 12:48 UTC, Mariangela commented on en/docs/develop/extending-api-manager/saml2-sso/configuring-identity-server-as-idp-for-sso.md
> +        [authentication.framework.extensions]
Do not keep spaces before entering the code in a code block

2020-12-07 05:42 UTC, Mariangela requested changes

2020-12-07 05:42 UTC, Mariangela commented on en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md
> +In the following document we will explain how to connect OKTA as a third party Identity provier to WSO2 API Manager.
@ruthryi , can you please review this entire document and update it, because it is not structured properly.

2020-12-10 07:53 UTC, Mariangela approved these changes
@ruthryi , as mentioned before please work on restructuring this content in [1]. Similar to what I did for doc [2] when I reviewed it fully. Please send it as a separate PR.

[1] en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-saml.md 
[2] en/docs/install-and-setup/setup/sso/okta-as-an-external-idp-using-oidc.md

2020-12-10 07:53 UTC, merged