Add security guidelines for admin accounts
wso2/docs-apim pull request #2278
Opened 2020-11-23 12:03 UTC by RakhithaRR

### Purpose
This PR adds production deployment related security guidelines for admin accounts.

2020-11-23 12:46 UTC, bhathiya requested changes

2020-11-23 12:46 UTC, bhathiya commented on en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
> +<td><p>Use a different admin user account to login into the system</p>
How about "Separate" instead of "Different"? @shaniR

2020-11-23 12:46 UTC, bhathiya commented on en/docs/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment.md
> +<td><p>WSO2 recommends that you use two seperate admin user accounts in production. One account for logging into the system and the other one as the system user in configurations (for internal servic
should these 2 be one single sentence? @shaniR

2020-12-03 16:35 UTC, Mariangela approved these changes

2020-12-03 16:41 UTC, merged