[Docs] [3.2.0] Fixes #2483 (Update graphQL rate limiting pages)
wso2/docs-apim pull request #2580
Opened 2020-12-21 08:45 UTC by Chamindu36

## Purpose
Fixing the capitalization and grammar issues in pages related to the GraphQL rate limiting

## Goals
Fixes https://github.com/wso2/docs-apim/issues/2483

## Approach
**/rate-limiting/graphql-api/overview-query-limits-for-graphql/ page**

![screenshot-localhost-8000-learn-rate-limiting-graphql-api-overview-query-limits-for-graphql-1608539323469](https://user-images.githubusercontent.com/42435576/102756918-8de9d780-4396-11eb-9e44-d7a75112310e.png)

**/rate-limiting/graphql-api/query-complexity-limitation/  page**
![Screenshot from 2020-12-21 14-05-22](https://user-images.githubusercontent.com/42435576/102756933-9215f500-4396-11eb-8742-83c9f472188b.png)

**/rate-limiting/graphql-api/query-depth-limitation/  page**
![screenshot-localhost-8000-learn-rate-limiting-graphql-api-query-complexity-limitation-1608539729103](https://user-images.githubusercontent.com/42435576/102756942-95a97c00-4396-11eb-8098-c71300e603fe.png)

2020-12-22 08:29 UTC, uvindra requested changes

2020-12-22 08:29 UTC, uvindra commented on en/docs/learn/rate-limiting/graphql-api/query-complexity-limitation.md
> +then the complexity should be at a high level but, if the field is easy to resolve and not a cheap operation,
This should read as,

`then the complexity should be at a high level, but if the field is easy to resolve(an inexpensive operation),`

2020-12-22 08:29 UTC, uvindra commented on en/docs/learn/rate-limiting/graphql-api/query-complexity-limitation.md
> +In the run time, the requested query complexity value will be calculated and, blocked if the value exceeds the max complexity.
This should read as,

`At runtime, a query will be blocked if its calculated complexity exceeds the specified max complexity.`

2020-12-22 08:29 UTC, uvindra commented on en/docs/learn/rate-limiting/graphql-api/query-complexity-limitation.md
> +If there are, no arguments provided in your requested query,  the complexity can be calculated simply by adding all the complexity values.
This should read as,

`If there are no arguments provided in a query,  the total complexity can be calculated by simply adding the individual complexity values of each field.`

2020-12-22 08:29 UTC, uvindra commented on en/docs/learn/rate-limiting/graphql-api/query-depth-limitation.md
> +This means a client could craft a query as follows:
This should read as,

`An example of such a query is as follows:`

2020-12-22 10:36 UTC, Chamindu36 commented on en/docs/learn/rate-limiting/graphql-api/query-complexity-limitation.md
> +the computation cost of resolving the particular field**.
Fixed

2020-12-23 05:03 UTC, uvindra approved these changes

2020-12-23 05:05 UTC, merged