Receiving events via Kafka and Publishing to WebSocket
wso2/docs-apim pull request #3477
Opened 2021-04-02 07:06 UTC by OshiWindsor

Added Receiving events via Kafka and Publishing to WebSocket tutorial

2021-04-02 07:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-apim?pullRequest=3477) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-apim?pullRequest=3477) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-apim?pullRequest=3477) it.</sub>

2021-04-03 08:42 UTC, samgnaniah commented on en/docs/use-cases/streaming-tutorials/receiving-events-via-kafka-and-publishing-to-websocket.md
> +The Streaming Integrator can consume events from a Kafka topic and publish those events to a WebSocket  in a streaming manner.
```suggestion
The Streaming Integrator can consume events from a Kafka topic and publish those events to a WebSocket in a streaming manner.
```

Shall we expand what we mean by "streaming manner"?

2021-04-05 03:11 UTC, samgnaniah commented on en/docs/use-cases/streaming-tutorials/receiving-events-via-kafka-and-publishing-to-websocket.md
> +5. Add the OSGI converted kafka libs from the `Destination` directory to the `<SI_HOME>/lib` directory.
```suggestion
5. Add the OSGI converted Kafka libs from the `Destination` directory to the `<SI_HOME>/lib` directory.
```

2021-04-05 03:11 UTC, samgnaniah commented on en/docs/use-cases/streaming-tutorials/receiving-events-via-kafka-and-publishing-to-websocket.md
> +1. Navigate to the `<KAFKA_HOME>` directory and start a zookeeper node by issuing the following command.
```suggestion
1. Navigate to the `<KAFKA_HOME>` directory and start a Zookeeper node by issuing the following command.
```

2021-04-05 03:12 UTC, samgnaniah commented on en/docs/use-cases/streaming-tutorials/receiving-events-via-kafka-and-publishing-to-websocket.md
> +You can limit the number of events as follows as well,
Does the number formatting break here?

2021-04-05 03:13 UTC, samgnaniah commented on en/docs/use-cases/streaming-tutorials/receiving-events-via-kafka-and-publishing-to-websocket.md
> +2. Open a terminal and navigate to the `<SIHome>/samples/sample-clients/websocket-receiver` directory and run the ant command.
```suggestion
2. Open a terminal and navigate to the `<SIHome>/samples/sample-clients/websocket-receiver` directory and run the `ant` command.
```

2021-04-05 03:13 UTC, samgnaniah commented on en/docs/use-cases/streaming-tutorials/receiving-events-via-kafka-and-publishing-to-websocket.md
> +Check the output in the terminal of <SIHome>/samples/sample-clients/websocket-receiver. You will see output similar to the following:
```suggestion
Check the output in the terminal of `<SI_HOME>/samples/sample-clients/websocket-receiver`. You will see output similar to the following: 
```

2021-04-05 04:16 UTC, OshiWindsor commented on en/docs/use-cases/streaming-tutorials/receiving-events-via-kafka-and-publishing-to-websocket.md
> +You can limit the number of events as follows as well,
No.

2021-04-05 04:49 UTC, samgnaniah approved these changes

2021-04-05 14:07 UTC, ramindu90 requested changes

2021-04-05 14:07 UTC, ramindu90 commented on en/docs/use-cases/streaming-tutorials/receiving-events-via-kafka-and-publishing-to-websocket.md
> +Provide the details in there for API Name, Context and Version where all fields are mandatory, and click on the **Create API** button.
Add an image of the entered details

2021-04-09 05:07 UTC, ramindu90 approved these changes

2021-04-09 05:07 UTC, merged