remove js sort on string versions
wso2/docs-apim pull request #3520
Opened 2021-04-07 21:39 UTC by vordimous

## Purpose
> remove js sort on string versions to prevent the incorrect ordering of the product version dropdown

2021-04-10 03:13 UTC, Mariangela commented
@erangatl , please review!

2021-04-10 03:13 UTC, Mariangela requested changes
@erangatl , please review this change.

2021-04-10 05:50 UTC, erangatl approved these changes

2021-04-11 18:59 UTC, Mariangela approved these changes

2021-04-11 18:59 UTC, merged

2021-04-11 18:59 UTC, Mariangela commented
@erangatl , please add this fix to the other branches if it is applicable.