Update screencaps
wso2/docs-apim pull request #3567
Opened 2021-04-11 06:27 UTC by samgnaniah

Fixes a couple of outdated screencaps.

2021-04-11 06:37 UTC, Mariangela requested changes
@samgnaniah , check what exactly we are trying to show in this screenshot.  Coz the old screen [2] had a recommended APIs for you section and this doesnt have that. But the name indicated that we are talking about recommended APIs.

[1] https://github.com/wso2/docs-apim/blob/18d9a7b0dd96b1084a5cb3c1fa9ba26ba1134e3c/en/docs/assets/img/learn/api-recommendations.png
[2] https://apim.docs.wso2.com/en/4.0.0-dev/assets/img/learn/api-recommendations.png

2021-04-11 06:39 UTC, samgnaniah commented
> @samgnaniah , check what exactly we are trying to show in this screenshot. Coz the old screen [2] had a recommended APIs for you section and this doesnt have that. But the name indicated that we are talking about recommended APIs.
> 
> [1] https://github.com/wso2/docs-apim/blob/18d9a7b0dd96b1084a5cb3c1fa9ba26ba1134e3c/en/docs/assets/img/learn/api-recommendations.png
> [2] https://apim.docs.wso2.com/en/4.0.0-dev/assets/img/learn/api-recommendations.png

Good question. I've assumed it just shows some APIs because of the way the content was worded but perhaps not. Let me check and update.

2021-04-12 07:22 UTC, samgnaniah commented
Updated screencap for API recommendations.

2021-04-12 07:34 UTC, Mariangela approved these changes

2021-04-12 07:35 UTC, merged