add a note on migration docs related to AM_API unique constraint
wso2/docs-apim pull request #3583
Opened 2021-04-12 12:39 UTC by isharac

## Purpose
w.r.t. https://github.com/wso2/carbon-apimgt/pull/10305

2021-04-15 14:35 UTC, Mariangela approved these changes

2021-04-15 14:37 UTC, Mariangela commented
@isharac , please build mkdocs locally when you introduce changes. That way you will be able to get the documentation formatting correct, because incorrect formatting can lead to the numbering breaking and also certain text not appearing.
Please resolve the merge conflicts in this PR.

2021-04-19 00:15 UTC, isharac commented
> @isharac , please build mkdocs locally when you introduce changes. That way you will be able to get the documentation formatting correct, because incorrect formatting can lead to the numbering breaking and also certain text not appearing.
> Please resolve the merge conflicts in this PR.

Fixed. Thanks.

2021-04-20 06:43 UTC, Mariangela requested changes
The changes done at review have been overridden when the merge conflict was resolved so this review changes need to be done again by the reviewer.

2021-04-22 11:39 UTC, Mariangela approved these changes

2021-04-22 11:39 UTC, merged