Removing unwanted 3.2.0 instances from API-M migration docs
wso2/docs-apim pull request #3816
Opened 2021-05-04 17:22 UTC by nilminiwso2

- Removed unwanted 3.2.0 references.

2021-05-04 17:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-apim?pullRequest=3816) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-apim?pullRequest=3816) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-apim?pullRequest=3816) it.</sub>

2021-05-05 11:52 UTC, Mariangela approved these changes

2021-05-05 11:58 UTC, merged

2021-05-05 12:04 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
> +        Run the [apim110_to_apim320_gateway_artifact_migrator.sh]({{base_path}}/assets/attachments/install-and-setup/apim110_to_apim320_gateway_artifact_migrator.sh) script, as shown below, to migrat
this step is not required in 4.0.0

2021-05-05 12:12 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
> +-   If you are using WSO2 Identity Server (WSO2 IS) as a Key Manager, first follow the instructions in [Upgrading WSO2 IS as the Key Manager to 5.10.0]({{base_path}}/install-and-setup/upgrading-wso2-
this should be identity server 5.11.0

2021-05-05 12:15 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
> +6.  Move all your Synapse configurations to the API-M 4.0.0 pack.
this step is not required.

2021-05-05 12:23 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
> +4.  Upgrade the WSO2 API Manager database from version 1.10.0 to version 4.0.0 by executing the relevant database script, from the scripts that are provided below, on the `WSO2AM_DB` database.
dbscripts should be ammended with queries needed to migrate from 3.2.0 -> 4.0.0

2021-05-05 12:27 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
> +        In API Manager 4.0.0, it is required to use a certificate with the RSA key size greater than 2048. If you have used a certificate that has a weak RSA key (key size less than 2048) in the prev
need to add below toml congiguration as well.

[keystore.tls]
file_name = "internal.jks"
type = "JKS"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

2021-05-05 12:28 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
> +        In API Manager 4.0.0, it is required to use a certificate with the RSA key size greater than 2048. If you have used a certificate that has a weak RSA key (key size less than 2048) in the prev
Also add below step after keystore configuration.

Configure the SymmetricKeyInternalCryptoProvider as the default internal cryptor provider. Generate your own secret key using a tool like OpenSSL.

i.e.,

 openssl enc -nosalt -aes-128-cbc -k hello-world -P
Add the configuration to the <NEW_IS_HOME>/repository/conf/deployment.toml file.

[encryption]
key = "<provide-your-key-here>"

2021-05-05 12:30 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
> +        In API Manager 4.0.0, it is required to use a certificate with the RSA key size greater than 2048. If you have used a certificate that has a weak RSA key (key size less than 2048) in the prev
IS version should be 5.11.0
need to change in all places.

2021-05-05 12:34 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
> +    2.  Copy the `migration-resources` folder from the extracted folder to the `<API-M_4.0.0_HOME>` directory.
is migration client should be taken from https://github.com/wso2-extensions/apim-identity-migration-resources/tags

2021-05-05 12:59 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
> +    5.  Copy the `org.wso2.carbon.is.migration-x.x.x.jar` from the `<IS_MIGRATION_TOOL_HOME>/dropins` directory to the `<API-M_4.0.0_HOME>/repository/components/dropins` directory.
need to skip following migrator configs also from the identity migration. 
    -
        name: "MigrationValidator"
        order: 2
    -
        name: "SchemaMigrator"
        order: 5
        parameters:
        location: "step2"
        schema: "identity"
    -
        name: "TenantPortalMigrator"
        order: 11  
        
        need to add these also in above step.

2021-05-05 13:19 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
this step needs to verify and add if required. Because in 4.0.0 we do not keep the synapse configs in the file system. @tharindu1st thoughts?

2021-05-05 13:21 UTC, isharac commented on en/docs/install-and-setup/upgrading-wso2-api-manager/upgrading-from-1100-to-400.md
> +       -   Remove the `migration-resources` and `migration-scripts` directories, which are in the `<API-M_4.0.0_HOME>` directory.
need to add below step after this.

Execute the following DB script in the respective AM database.

??? info "DB Scripts" ```tab="DB2" ALTER TABLE AM_API ADD CONSTRAINT API_UUID_CONSTRAINT UNIQUE(API_UUID) /

 ```
 
 ```tab="MySQL"
 ALTER TABLE AM_API ADD CONSTRAINT API_UUID_CONSTRAINT UNIQUE(API_UUID);

 ```
         
 ```tab="MSSQL"
 ALTER TABLE AM_API ADD CONSTRAINT API_UUID_CONSTRAINT UNIQUE(API_UUID);

 ``` 

 ```tab="PostgreSQL"
 ALTER TABLE AM_API ADD CONSTRAINT API_UUID_CONSTRAINT UNIQUE(API_UUID);

 ```
         
 ```tab="Oracle"
 ALTER TABLE AM_API ADD CONSTRAINT API_UUID_CONSTRAINT UNIQUE(API_UUID)
 /

 ```

2021-05-05 13:24 UTC, isharac requested changes
I have commented on 1.10.0 -> 4.0.0 migration doc fo the required changes. same changes should go in 1.8/1.9/1.9.1 doc as well.

However, we need to test the docs.