Update Product API Definitions
wso2/docs-apim pull request #4058
Opened 2021-05-19 20:04 UTC by msm1992

## Purpose
Related 4.0.0 PR : https://github.com/wso2/docs-apim/pull/3970

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2021-05-20 18:05 UTC, Mariangela requested changes

2021-05-20 18:05 UTC, Mariangela commented on en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
> +          description: The user roles that are able to access the API in Devportal
```suggestion
          description: The user roles that are able to access the API in the Developer Portal
```

2021-05-20 18:05 UTC, Mariangela commented on en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
> +              description: Id of policy
```suggestion
              description: ID of the policy
```

2021-05-20 18:05 UTC, Mariangela commented on en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
> +              description: Throttling policy tenant domain id
```suggestion
              description: Throttling policy tenant domain ID
```

2021-05-20 18:05 UTC, Mariangela commented on en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
> +                define whether this is Paid or a Free plan. Allowed values are FREE or COMMERCIAL.
```suggestion
                Defines whether this is Paid or a Free plan. Allowed values are FREE or COMMERCIAL.
```

2021-05-20 18:05 UTC, Mariangela commented
@msm1992 , please apply the new review comment changes to 4.0.0 as well.

2021-05-21 11:02 UTC, msm1992 commented on en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
> +                  description: Definition url
should be corrected to 'API Definition URL'

2021-05-21 11:02 UTC, msm1992 commented on en/docs/reference/product-apis/publisher-apis/publisher-v2/publisher-v2.yaml
> +        Update deployment devportal visibility
Should be 'Update deployment'

2021-05-21 11:19 UTC, msm1992 commented on en/docs/reference/product-apis/devportal-apis/devportal-v2/devportal-v2.yaml
> +        Get a list of available topics for a given async API
Updated to 'Get a list of available topics for a given Streaming API'

2021-06-21 04:25 UTC, Mariangela approved these changes

2021-06-21 04:25 UTC, Mariangela commented
@msm1992 , please make sure that these changes are in 400 as well

2021-06-21 04:25 UTC, merged