Update create-and-publish-websocket-api.md
wso2/docs-apim pull request #4543
Opened 2021-08-24 11:08 UTC by samgnaniah

Fixes https://github.com/wso2/docs-apim/issues/3563

2021-08-24 16:10 UTC, Mariangela approved these changes

2021-08-24 16:13 UTC, Mariangela requested changes
@samgnaniah , this may be better off in the Troubleshoot guide and we can add a link to that section in this page. So that the info on troubleshooting does not get scattered.

2021-08-25 03:21 UTC, chanikag approved these changes

2021-08-25 04:13 UTC, samgnaniah commented
> @samgnaniah , this may be better off in the Troubleshoot guide and we can add a link to that section in this page. So that the info on troubleshooting does not get scattered.

Let's merge this. I'll send a separate PR for that change.

2021-08-25 05:15 UTC, Mariangela approved these changes

2021-08-25 05:15 UTC, merged