Dynamic Endpoint Sample | Mediation Extensions
wso2/docs-apim pull request #4641
Opened 2021-09-06 09:01 UTC by ruthryi

A -  808

2021-09-06 10:36 UTC, samgnaniah commented on en/docs/learn/api-gateway/message-mediation/adding-dynamic-endpoints.md
> +    The dynamic endpoint functionality is suitable for scenarios where the application client can send an attribute in the request correlating to the intended endpoint (such as an HTTP transport head
```suggestion
    The dynamic endpoint functionality is suitable for scenarios where the application client can send an attribute in the request correlating to the intended endpoint (such as an HTTP transport header or as part of the payload), which can be used in the mediation extension.
```

2021-09-06 10:50 UTC, samgnaniah commented on en/docs/learn/api-gateway/message-mediation/changing-the-default-mediation-flow-of-api-requests.md
> +1. You can copy the above mediation sequence into a **XML** file.
```suggestion
1. You can copy the above mediation sequence into an **XML** file.
```

2021-09-06 10:51 UTC, samgnaniah commented on en/docs/learn/api-gateway/message-mediation/changing-the-default-mediation-flow-of-api-requests.md
> +1.  Go to the Edit option in the **Message Mediation** section.
```suggestion
1.  Go to the **Edit** option in the **Message Mediation** section.
```

2021-09-06 19:06 UTC, lkokila requested changes

2021-09-06 19:06 UTC, lkokila commented on en/docs/learn/api-gateway/message-mediation/changing-the-default-mediation-flow-of-api-requests.md
> +    The mediation extension is applied to all resources of the API. Therefore, all resources will contain a similar logic to construct the endpoint.
@ruthryi  This document contains details about mediation sequences in general. Let's remove the "Therefore, all resources will contain a similar logic to construct the endpoint." part here.

2021-09-07 07:37 UTC, samgnaniah approved these changes

2021-09-07 07:37 UTC, merged