[DO NOT MERGE] Update dashboard document for Kubernetes environment
wso2/docs-apim pull request #4712
Opened 2021-09-21 17:19 UTC by dulanjalidilmi

## Purpose
Update docs for https://github.com/wso2/micro-integrator/issues/2135

2021-09-22 12:32 UTC, samgnaniah commented on en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
> +    If MI server is deployed in a Kubernetes environment, add following configuration too to the `deployment.toml`.
```suggestion
    If the Micro Integrator server is deployed in a Kubernetes environment, add the following configuration to the `deployment.toml` file. 
```

2021-09-22 12:33 UTC, samgnaniah commented on en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
> +    Limitation: Currently the dashboard does not support deployments with replicas
```suggestion
    Limitation: Currently the dashboard does not support deployments with replicas.
```

2021-09-22 12:34 UTC, samgnaniah commented on en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
> +    If communication via Ingress:
```suggestion
    If communicating via Ingress, use the following configuration:
```

2021-09-22 12:34 UTC, samgnaniah commented on en/docs/observe/mi-observe/working-with-monitoring-dashboard.md
> +    If communication via Service
```suggestion
    If communicating via Service instead, use the following configuration:
```

2021-09-23 06:15 UTC, Mariangela requested changes
DO NOT MERGE ATM

2021-09-23 07:49 UTC, samgnaniah approved these changes

2021-09-24 08:06 UTC, merged