[Master] Add http_access log config and Fixes #3324 issue
wso2/docs-apim pull request #4732
Opened 2021-09-24 06:48 UTC by Chamindu36

## Purpose
Add configuration to this doc [1] for the change done in this PR [2].

With the existing access log valve, the application's access logs get recorded or written into the http_access.log. file. This config enables a new valve that allows logs to get written into the wso2carbon.log or any other log file and show up on the console.

```
[http_access_log]
useLogger = true
```
[1].https://apim.docs.wso2.com/en/latest/observe/api-manager/monitoring-http-access-logs/
[2]. https://github.com/wso2/carbon-kernel/pull/2661

## Goals

1. Add the new config under the relevant topic in Master docs.
2. Add new config into configuration catalog [3].
3. Fixes #3324 for Master documentation.

[3]. https://apim.docs.wso2.com/en/latest/reference/config-catalog/

## Approach

![ScreenShot Tool -20210924114125](https://user-images.githubusercontent.com/42435576/134627761-09db417d-872e-4ae6-bc14-7601ea4115e7.png)

![ScreenShot Tool -20210924114636](https://user-images.githubusercontent.com/42435576/134627769-376a94a7-5284-4826-afdb-a17983605532.png)

2021-09-24 07:02 UTC, samgnaniah approved these changes

2021-09-24 07:04 UTC, samgnaniah commented on en/docs/observe/api-manager/monitoring-http-access-logs.md
> +In the API Manager access logs of applications get recorded or written into the `<APIM_HOME>repository/logs/http_access_.log` file. The following config enables a new valve that allows logs to get wr
```suggestion
In the API Manager, access logs of applications get recorded or written into the `<APIM_HOME>repository/logs/http_access_.log` file. The following config enables a new valve that allows logs to get written into the `<APIM_HOME>repository/logs/wso2carbon.log` or any other log file and show up on the console.
```

2021-09-24 07:06 UTC, samgnaniah commented
I think config catalog changes need to be made in the JSON file. @ruthryi can you have a look and see if this is ok?

2021-09-24 07:22 UTC, ruthryi requested changes
Config catalog related changes should be added in - docs-apim/en/tools/config-catalog-generator/data/configs.json
Please follow the instructions in https://github.com/wso2/docs-apim/blob/master/en/tools/config-catalog-generator/README.md

2021-09-30 06:20 UTC, ruthryi approved these changes

2021-09-30 06:25 UTC, merged