added publisher read only mode docs
wso2/docs-apim pull request #5098
Opened 2021-12-02 06:08 UTC by hasuniea

## Purpose
> Added documentation for the publisher read only mode feature.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2022-01-05 05:43 UTC, 1akshitha commented
@Mariangela can we please get this merged ASAP. This is a blocker for the M3 release which is scheduled for this week.

2022-01-05 16:56 UTC, Mariangela requested changes
@hasuniea , please note my comment and see the suggestions I have added please.

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +A user who has the view/read only permissions can only view the API, API Product and Service details in the publisher
```suggestion
A user who has the view/read only permissions can only view the API, API Product and Service details in the Publisher
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +#### Read Only User:
```suggestion
#### Read Only User
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +The user has only the apim:api_view permission.
```suggestion
The user has only the `apim:api_view` permission.
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +Let's create a read only user and experience the publisher portal in read only mode.
```suggestion
Let's create a read only user and experience the Publisher portal in read only mode.
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +Steps to create a Read only user:
```suggestion
Follow the instructions below to create a Read only user:
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +1. Create role ex: read_only in admin console
```suggestion
1. Create role (e.g., `read_only`) in admin console.
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +3. Assign the login permission to login to the publisher portal via the admin console.
```suggestion
3. Assign the login permission to login to the Publisher portal via the admin console.
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +4. Login to the admin portal and navigate to scope management under the Settings subheading.
```suggestion
4. Log in to the Admin Portal and navigate to **scope management** which is under **Settings**.
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +5. Click on the add scope mappings.
```suggestion
5. Click **Add Scope Mappings**.
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +   Under the Role name please give the Role as read_only(the role you assigned to the read only user).
```suggestion
   Enter the Role name as `read_only` (This is the role you assigned to the read only user).
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +   Check apim:api_view permission under the publisher.
```suggestion
   Check the `apim:api_view` permission under the Publisher.
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/design/api-security/authorization/publisher-portal-in-read-only-mode.md
> +ex: API detail view
```suggestion
Example: API detail view
```

2022-01-05 16:56 UTC, Mariangela commented on en/docs/get-started/about-this-release.md
> +     A user who has view/read only permissions can only view the API/Services details in the publisher portal.He/She should not be able to edit/create/publish APIs/Services.
```suggestion
     A user who has view/read only permissions can only view the API/Services details in the Publisher portal. Such users should not be able to edit/create/publish APIs/Services.
```

2022-01-06 10:47 UTC, Mariangela approved these changes

2022-01-06 10:47 UTC, Mariangela commented on en/mkdocs.yml
> +              'learn/api-security/authorization/publisher-portal-in-read-only-mode.md': 'https://apim.docs.wso2.com/en/4.0.0/design/api-security/authorization/publisher-portal-in-read-only-mode/'
```suggestion
```

2022-01-06 10:51 UTC, merged