Improve Streaming Integrator Quick Start Guide
wso2/docs-apim pull request #6815
Opened 2023-03-03 10:35 UTC by SanojPunchihewa

## Purpose
Fixes https://github.com/wso2/docs-apim/issues/6732

2023-03-03 11:42 UTC, AnuGayan approved these changes

2023-03-03 12:43 UTC, senthuran16 requested changes

2023-03-03 12:43 UTC, senthuran16 commented on en/docs/get-started/streaming-quick-start-guide.md
>  3. Click on **New**, and copy and paste the content given below.
```suggestion
3. Click on **New**, and copy and paste the content given below.
    !!! Note
        The Siddhi application given below listens to the `/Users/foo/files` directory. You will be copying files to this directory in the upcoming steps. Create this directory if you haven't done it, or use another directory by specifying it in the `dir.uri = 'file:/Users/foo/files'` parameter in the Siddhi application.
```

2023-03-03 12:43 UTC, senthuran16 commented on en/docs/get-started/streaming-quick-start-guide.md
> +1. Copy the `sampledata.xml` file downloaded in step 3.1 to the `/Users/foo/files` directory.
```suggestion
1. Copy the `sampledata.xml` file downloaded in step 3.1 to the `/Users/foo/files` directory (or the directory that was specified in step 3.3). 
```

2023-03-03 12:43 UTC, senthuran16 commented on en/docs/get-started/streaming-quick-start-guide.md
> +     - For testing purposes, you skip the above and simply copy the keystore and the truststore of APIM to SI and SI Tooling.
```suggestion
     - For testing purposes, you can skip the above and simply copy the keystore and the truststore of WSO2 APIM (`wso2carbon.jks` and `client-truststore.jks` files located in the `<WSO2_APIM_HOME>/repository/resources/security/` directory) to the `resources/security` directory of **both** SI and SI Tooling.
     - Restart SI and SI Tooling.
```

2023-03-03 12:43 UTC, senthuran16 commented on en/docs/get-started/streaming-quick-start-guide.md
> +        - If wscat is not already install, use the following command to install it,
```suggestion
        - If wscat is not already installed, use the following command to install it:
```

2023-03-03 12:43 UTC, senthuran16 commented on en/docs/get-started/streaming-quick-start-guide.md
> +        - If wscat is not already install, use the following command to install it,
```suggestion
        - If `wscat` is not already installed, use the following command to install it:
```

2023-03-07 05:40 UTC, senthuran16 approved these changes

2023-03-07 05:47 UTC, merged